### ISSUE TITLE
problem importing multicolor bitmaps on c64

### ISSUE THREAD

**Issue by Zorglub47** [daad-adventure-writer/MALUVA#16]
Hi. I can successfully load hi-res pictures created in  multipaint on mac using sc2daad command 

./sc2daad c64 test0.art 001.64 96

and get expected pixel perfect results, but when using a multicolor image koala image also from multipaint

./sc2daad c64 test01.kla 002.64 96 

the result is strange. I get some pallette issue. See attached screenshots for difference
![multicolor](https://user-images.githubusercontent.com/47294343/144581692-30df0ad5-cd7e-487c-b577-3c18a3e9345e.png)
![hires](https://user-images.githubusercontent.com/47294343/144581697-fd35010b-f315-406e-ab3b-20ebcb5e181a.png)

**Comment by Utodev** [comment]
I assume the lower picture is the Hires one, and the upper picture is the multipaint one. If so, firt of all I have to ask if you have set split mode, which is done by running "XSPLITSCR 1" condAct in the source DSF file. You can do it when the game starts so the split mode (multicolor in the first half of screen, hires at the bottom) is enabled, otherwise you are loading Multicolor pictures whiel in Hires resolution.

Please notice the split screen mode has some limitations, as although it's commonly used in C64, it was not originally implemented in DAAD, so including it has been a bit tricky. The limitations are:

- Image height should be 96 pixels and no other
- It's possible to see some artifacts in screen in around the split line, so it's recommended that the last few lines of that picture are empty (blank).
- As it requires interrupts to be working, and it's impossible to keep them on while reading from disk, it's recommended to clear the screen while loading, or a lot of artifacts will be on screen.

I hope your only problem was missing the XSPLITSCR call, if not , please provide details of Multipaint version, and if you can, send links to KLA files for further testing.

**Comment by Zorglub47** [comment]
Hi Uto !

Cudos, you are right, when I apply XSPLITSCR 1 at the end of the /PRO 0 section, I get to display the multicolor bitmap (koala) picture correctly. This is exactly what Im after and it works like a charm. Thank you for your support ! 

/Christian

**Comment by Utodev** [comment]
Nice that it worked!

It would be good though, that you put that call somewhere in /PRO 6, or if in PRO 0, just before calling PROCESS 6. That would make it be run only on initialization, while at the end of process 0 calls it every time a new location is described. With other condacts that wouldn't be a problem but XSPLITSCR works with interrupts and I've found it becomes unstable after too much calling it, specially in real machine, although I've seen that happen in emulators too.

I'm closing this issue now, no need to answer :-)
